language: node_js
node_js:
  - 0.10
env:
  CODECLIMATE_REPO_TOKEN=63c3fda700cd462c18dfd8787b032668d4a4242fe25b5962505222e77994ab1e
before_script:
  - npm i -g gulp jspm codeclimate-test-reporter 
  - npm i
  - jspm i
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - jspm dl-loader --traceur
  - gulp test:unit
  - gulp test:e2e
  - jspm dl-loader --6to5
  - gulp test:unit
  - gulp test:e2e
  - gulp report:ci
  - cat report/lcov/firefox/lcov.info |  codeclimate
  - gulp doc:test
  - gulp serve:test

